### ISSUE TITLE
Allow multiselection / export + import of multiple textures

### ISSUE THREAD

**Issue by SK83RJOSH** [niftools/nifskope#183]
I'm attempting to dump all the textures from Bully: Scholarship edition. This particular game runs a custom version of Gamebryo, and separates it's model archives from it's texture archives. So I need to open up a couple hundreds texture archive and manually export every single texture one by one. This is rather inefficient.

My proposal, which I think would be generally useful for people looking to dump textures, and not necessarily models:

Allow multi-selection of nodes in the tree, or add options similar to "Export .OBJ" and "Import .OBJ". They would be called "Export Textures" and "Import Textures" where exporting dumps them to a specified folder with the original base names. Importing multiple files would overwrite the data for existing textures with the new image. If a file does not already exist, I suppose it could prompt you for additional information if applicable.

**Comment by SK83RJOSH** [comment]
I see that this may be a partial duplicate of #34, and seeing as this project has almost entirely stalled... I suppose that won't be implemented any time soon. I have a question for you @neomonkeus since @jonwd7 seems like he's disappeared from the face of the earth. Is this project completely stalled and unlikely to reboot any time soon? Is there an interest in having someone pick up maintaining this repository?

**Comment by hexabits** [comment]
You'd have a hard time finding someone interested in a non-Bethesda game as the maintainer, which wouldn't really help your issue.

**Comment by SK83RJOSH** [comment]
@jonwd7 considering the tool is meant to support a variety of titles using _GameBryo_ and not necessarily _Bethesda_ titles, I disagree. The fact of the matter is this code base is monolithic and difficult to get into, and that'd be the real challenge. That said I implemented this functionality myself after creating this issue. I had intentions to PR it back into this repository, and volunteer to assist with the backlog -- hence my comment.

Based on your comment though, where you don't clarify the status of this repository, I won't. :)

**Comment by hexabits** [comment]
> considering the tool is meant to support a variety of titles using GameBryo and not necessarily Bethesda titles, I disagree

Not sure why you would disagree with the fact that there are virtually no active Gamebryo modding communities outside of Bethesda games, at least not **active or large enough** to likely contain someone capable of maintaining this.  What I said wasn't an opinion to be disagreed with, it's a matter of probability.  I'm sorry you misread. 

If you want an actual opinion about appropriate maintainers, it *isn't* a very good idea for it to be someone who isn't extremely well versed in Bethesda's 20.2 format, considering 99.9% of the application's userbase uses it for working on that version. 

> I won't. :)

FYI, someone vindictive shouldn't contribute to or maintain the repository anyway.  You gave no indication you were interested in or capable of figuring it out on your own or I would have responded much differently.  Your second comment appeared to be out a single-minded interest in a single game (Bully, which is your right), and you certainly weren't offering yourself up for the position, so I gave you the most honest and helpful reply I could.   So, it's a bit bewildering you for to swoop in in the third act, dangle an alleged solution, boast about how you won't share it, and then close a perfectly valid ticket.

**Comment by HetchAlDim** [comment]
@SK83RJOSH any chance you still have the version of NifSkope where you added the bulk export yourself? I'm having a similar issue trying to export W101 textures.

**Comment by SK83RJOSH** [comment]
> @SK83RJOSH any chance you still have the version of NifSkope where you added the bulk export yourself? I'm having a similar issue trying to export W101 textures.

Unfortunately I don't think so, the PC I made those changes on has long since been wiped, and I don't think I pushed anything. I was waiting to get a confirmation that this project had a maintainer before doing bulk importing and opening a pull request. Unfortunately things got heated though, and nothing ever came of my work, so my apologies for that.

If it's something that will save you a lot of time and you only need exporting I can probably take a look at reimplementing it this weekend/finding an old backup. If you'd like that, feel free to add me on discord (same username as GitHub), and send me some sample files. No promises of course, but I can probably throw something together again.

**Comment by SK83RJOSH** [comment]
> You gave no indication you were interested in or capable of figuring it out on your own or I would have responded much differently.

It's neither here nor there at this point, but I apologize for escalating the situation. Your responses came across as fairly abrasive at the time, and it was the height of lockdown when things were pretty dreary and stressful, so I was wound up pretty tightly as a result. Definitely could have handled this with more tact, so I do apologize, you likely didn't need the extra stress at the time either.

**Comment by HetchAlDim** [comment]
> Unfortunately I don't think so, the PC I made those changes on has long since been wiped, and I don't think I pushed anything. I was waiting to get a confirmation that this project had a maintainer before doing bulk importing and opening a pull request. Unfortunately things got heated though, and nothing ever came of my work, so my apologies for that.
> 
> If it's something that will save you a lot of time and you only need exporting I can probably take a look at reimplementing it this weekend/finding an old backup. If you'd like that, feel free to add me on discord (same username as GitHub), and send me some sample files. No promises of course, but I can probably throw something together again.

That would be awesome. Yeah I spend lots of time just exporting textures to dds lol, I added you!

**Comment by BenParsley** [comment]
Its amazing to see there is still a somewhat active community within Niftools - especially so for products that rely on NIF Data Formats. 

If there is any updates regarding a _multiple select / export + import of multiple textures_ feature I would love to hear about it. I've attempted to send you a message @SK83RJOSH via Discord 😉

**Comment by SK83RJOSH** [comment]
Heya, I ended up being swamped this past weekend but I'm still planning to take a look. Should be able to do something with the export side, importing is the only thing I'd like to avoid doing since it's a bit painful. :)
